api/urls.py
from django.urls import (
    path,
    include,
)
from rest_framework.routers import (
    # SimpleRouter,
    DefaultRouter,
)
from api.views import CategoryViewSet
from api import api_views, generic_views, view_sets, filter_views, pagination_views

router = DefaultRouter()
router.register('categories', CategoryViewSet)
router.register('base', view_sets.CategoryViewSet, basename='base')
router.register('model', view_sets.CategoryModelViewSet, basename='model')
router.register('custom', view_sets.CategoryCustomViewSet, basename='custom')

# filter
router.register('queryset', filter_views.CategoryQuerysetFilterViewSet, basename='queryset')
router.register('param', filter_views.CategoryParamFilterViewSet, basename='param')
router.register('django', filter_views.CategoryDjangoFilterViewSet, basename='django')
router.register('custom-django', filter_views.CategoryCustomDjangoFilterViewSet,
                basename='custom-django')

# pagination
router.register('pagenumber', pagination_views.CategoryPageNumberPaginationViewSet,
                basename='pagenumber')
router.register('limitoffset', pagination_views.CategoryLimitOffsetPaginationviewSet,
                basename='limitoffset')


app_name = 'api'

urlpatterns = [
    # API views
    path('views/api-view/', api_views.CategoryAPIView.as_view()),
    path('views/func-api-view/', api_views.category_view),

    # generic views
    path('generic/create/', generic_views.CategoryCreateAPIView.as_view()),
    path('generic/list/', generic_views.CategoryListAPIView.as_view()),
    path('generic/retrieve/<int:pk>/', generic_views.CategoryRetrieveAPIView.as_view()),
    path('generic/destroy/<int:pk>/', generic_views.CategoryDestroyAPIView.as_view()),
    path('generic/update/<int:pk>/', generic_views.CategoryUpdateAPIView.as_view()),

    # подключаем интерфейс
    path('viewsets/', include(router.urls)),

    # filter
    path('filters/kwargs/<str:name>/', filter_views.CategoryKwargsFilterView.as_view()),

]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('category/list/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('animal/list/', views.AnimalListView.as_view(), name='animal_list'),
    path('animal/create/', views.AnimalCreateView.as_view(), name='animal_create'),

    path('contact/', views.ContactFormView.as_view(), name='contact'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import routers, serializers, viewsets
# from user_app.models import MyUser
#
#
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = MyUser
#         fields = ['url', 'username', 'email', 'is_staff']
#
#
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = MyUser.objects.all()
#     serializer_class = UserSerializer
#
#
# router = routers.DefaultRouter()
# router.register(r'api-users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include('user_app.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]

mainapp/models.py
from django.db import models


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimeStampMixin):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f'{self.name}'

    @property
    def title_name(self):
        return self.name.upper()


class Food(TimeStampMixin):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


class Animal(TimeStampMixin):
    name = models.CharField(max_length=100)
    # 1 - 1, 1 - *, * - *
    # 1 категория - много животных
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    food = models.ManyToManyField(Food)

    def __str__(self):
        return f'{self.name}'

    @property
    def show_food(self):
        food = []
        food_queryset = self.food.all()
        for food_obj in food_queryset:
            food.append(food_obj.name)
        food_str = ', '.join(food)
        return food_str

    def get_category_name(self):
        return self.category.name


class WildAnimal(Animal):
    age = models.PositiveSmallIntegerField(default=0, null=True, blank=True)


class HomeAnimal(Animal):
    last_owner_name = models.CharField(max_length=100, blank=True, null=True)


class AnimalCard(TimeStampMixin):
    animal = models.OneToOneField(Animal, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)

mainapp/forms.py
from django import forms
from .models import Animal, Category, Food


class AnimalForm(forms.ModelForm):
    # просто форма для написания текста в 1 строку
    name = forms.CharField(label='Имя',
                           # обязательное для заполнения поле или нет
                           required=True,
                           # вид поля Textarea или TextInput
                           widget=forms.TextInput(
                               attrs={'placeholder': 'Input animal name',
                                      # указывается для того, чтобы заработал bootstrap
                                      'class': 'form-control', }
                           )
                           )

    category = forms.ModelChoiceField(
        label='Категория',
        # queryset - выборка
        queryset=Category.objects.all(),
        required=True,
        widget=forms.Select(
            attrs={'class': 'form-control'}
        )
    )

    food = forms.ModelMultipleChoiceField(
        label='Еда',
        queryset=Food.objects.all(),
        required=True,
        widget=forms.CheckboxSelectMultiple(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = Animal
        fields = '__all__'
        # fields = ('name', 'category')
        # exclude = ('category',)


class ContactForm(forms.Form):
    # Наследование от простых форм, т.к. ничего не сохраняем в модель
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.db.models import Case, When, Value, IntegerField
from mainapp.models import Category, Animal
from mainapp.forms import AnimalForm, ContactForm


# данные запроса
def index_view(request):
    return render(request, 'mainapp/index.html')


# def category_list_view(request):
#     category_list = Category.objects.all()
#     context = {'category_list': category_list}
#     return render(request, 'mainapp/category_list.html', context=context)


class CategoryListView(ListView):
    model = Category
    # ordering определяет как происходит сортировка
    ordering = ['pk']  # ordering = ['name']

    # пагинация - сколько объектов выводить на страницу
    # paginate_by = 5

    # передать свойства внутрь класса
    # template_name =

    # названия переменной в шаблоне
    # context_object_name =

    # get - гет запрос

    # get_queriset - получение данных

    # если мы хотим добавить что-то в контекст / передача контекста в шаблон
    # get_context_data
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['some_text'] = "some text"
        return context


class CategoryDetailView(DetailView):
    model = Category

    # get - гет запрос
    # get_context_data - передача контекста в шаблон
    # get_queriset - получение данных
    # get_object - получение одного объекта


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy('mainapp:category_list')

    # get - гет запрос
    # get_context_data - передача контекста в шаблон
    # post
    # form_valid
    # get_success_url


class CategoryUpdateView(UpdateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy('mainapp:category_list')

    # get - гет запрос
    # get_context_data - передача контекста в шаблон
    # post
    # form_valid
    # get_object - получение одного объекта
    # get_success_url


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = reverse_lazy('mainapp:category_list')

    # get - гет запрос
    # get_context_data - передача контекста в шаблон
    # post
    # form_valid
    # get_object
    # get_success_url


class AnimalListView(ListView):
    model = Animal
    template_name = 'mainapp/animals.html'

    def get_queryset(self):
        # Все животные
        queryset = Animal.objects.select_related('wildanimal').annotate(
            age=Case(
                When(wildanimal__isnull=False, then='wildanimal__age'),
                default=Value(None),
                output_field=IntegerField()
            )
        )

        queryset = queryset.select_related('category')
        queryset = queryset.prefetch_related('food')

        return queryset


class AnimalCreateView(CreateView):
    """Представление для создания животных"""

    model = Animal
    form_class = AnimalForm
    success_url = reverse_lazy('mainapp:animal_list')


class ContactFormView(FormView):
    form_class = ContactForm
    success_url = reverse_lazy('mainapp:index')
    template_name = 'mainapp/contact.html'

    # Переопределяем метод
    def form_valid(self, form):
        data = form.cleaned_data
        print('MESSAGE', data['message'])
        return super().form_valid(form)

mainapp/templates/mainapp/animal_form.html
{% extends "base.html" %}
{% block title %}
Create animal
{% endblock %}

{% block body %}


<div class="container">
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <hr>
            {{field.label}}
            {{field}}
            {% if field.errors%}
                {% for error in field.errors %}
                    <p class="text text-primary">{{error}}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}
        <hr>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/animals.html
{% extends "base.html" %}
{% block title %}
Animals
{% endblock %}
{% block body %}


<div class="container">
    {% with object_list.count as object_count %}
    <h2>Количество животных: {{object_count}}</h2>
    <p></p>
    <!-- Example row of columns -->
    <div class="row">
        {% for object in object_list %}
        <div class="col-lg-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ object.name }}</h5>
                    <p class="card-text">{{ object.category.name }}</p>
                    {% if object.age %}
                    <p class="card-text">Возраст: {{object.age}}</p>
                    {% else %}
                    <p class="card-text">Возраст: Не указан</p>
                    {% endif %}

                    {% if object.food.exists %}
                    <p>Food:</p>
                    <ul class="list-group">
                        {% for food in object.food.all %}
                        <li class="list-group-item">
                            {{ food.name }}
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endwith %}
    <p>
        <a class="btn btn-info" href="{% url 'mainapp:animal_create' %}">Create</a>
    </p>
</div>
{% endblock %}

mainapp/templates/mainapp/category_confirm_delete.html
{% extends "base.html" %}
{% block title %}
    {{object.name}}
{% endblock %}

{% block body %}


<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-lg-3">
            <div class="card" style="width: 18rem;">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        {{category.name}}
                    </h5>
                    <p class="card-text text-danger">Вы действительно хотите удалить?</p>
                    <form method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn-outline-light">YES</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/category_detail.html
{% extends "base.html" %}
{% block title %}
{{object.name}}
{% endblock %}

{% block body %}


<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-lg-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">
                        {{category.name}}
                    </h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/category_form.html
{% extends "base.html" %}
{% block title %}
    {{object.name}}
{% endblock %}

{% block body %}


<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/category_list.html
{% extends "base.html" %}
{% block title %}
Categories
{% endblock %}

{% block body %}


<div class="container">
    {% with category_list.count as count %}
    <h2>Количество категорий животных: {{count}}</h2>
    <p></p>
    <!-- Example row of columns -->
    <div class="row">
        {% for category in category_list %}
        <div class="col-lg-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'mainapp:category_detail' pk=category.pk %}">
                            {{category.name}}
                        </a>
                    </h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="{% url 'mainapp:category_update' pk=category.pk %}" class="btn btn-success">Update</a>
                    <a href="{% url 'mainapp:category_delete' pk=category.pk %}" class="btn btn-primary">Delete</a>
                    <a href="{% url 'mainapp:animal_list' %}?category_id={{category.id}}" class="btn btn-danger">Get
                        Animals</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endwith %}
    <p></p>
    <a class="btn btn-info" href="{% url 'mainapp:category_create' %}">Create</a>
    <hr>
    <p class="text-warning">{{some_text}}</p>
</div>
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends "base.html" %}
{% block title %}
   Contact
{% endblock %}

{% block body %}


<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Zoo
{% endblock %}

{% block body %}

<div class="text-center rounded-3">
    <img src="{% static 'images/logo.png' %}" class="bi mt-4 mb-3" width="100" height="100">
    <h1 class="text-body-emphasis">Welcome to Zoo!</h1>
    <p class="col-lg-8 mx-auto fs-5 text-muted">
      You can find your little friends here
    </p>
    <div class="d-inline-flex gap-2 mb-5">
        <a class="d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill" href="{% url 'mainapp:category_list' %}">Categories</a>
      <a class="btn btn-outline-secondary btn-lg px-4 rounded-pill" href="{% url 'mainapp:contact' %}">Contact</a>
    </div>
  </div>


{% endblock %}