api/urls.py
from django.urls import (
    path,
    include,
)
from rest_framework.routers import (
    # SimpleRouter,
    DefaultRouter,
)
from api.views import CategoryViewSet
from api import api_views, generic_views, view_sets, filter_views, pagination_views

router = DefaultRouter()
router.register('categories', CategoryViewSet)
router.register('base', view_sets.CategoryViewSet, basename='base')
router.register('model', view_sets.CategoryModelViewSet, basename='model')
router.register('custom', view_sets.CategoryCustomViewSet, basename='custom')

# filter
router.register('queryset', filter_views.CategoryQuerysetFilterViewSet, basename='queryset')
router.register('param', filter_views.CategoryParamFilterViewSet, basename='param')
router.register('django', filter_views.CategoryDjangoFilterViewSet, basename='django')
router.register('custom-django', filter_views.CategoryCustomDjangoFilterViewSet,
                basename='custom-django')

# pagination
router.register('pagenumber', pagination_views.CategoryPageNumberPaginationViewSet,
                basename='pagenumber')
router.register('limitoffset', pagination_views.CategoryLimitOffsetPaginationviewSet,
                basename='limitoffset')


app_name = 'api'

urlpatterns = [
    # API views
    path('views/api-view/', api_views.CategoryAPIView.as_view()),
    path('views/func-api-view/', api_views.category_view),

    # generic views
    path('generic/create/', generic_views.CategoryCreateAPIView.as_view()),
    path('generic/list/', generic_views.CategoryListAPIView.as_view()),
    path('generic/retrieve/<int:pk>/', generic_views.CategoryRetrieveAPIView.as_view()),
    path('generic/destroy/<int:pk>/', generic_views.CategoryDestroyAPIView.as_view()),
    path('generic/update/<int:pk>/', generic_views.CategoryUpdateAPIView.as_view()),

    # подключаем интерфейс
    path('viewsets/', include(router.urls)),

    # filter
    path('filters/kwargs/<str:name>/', filter_views.CategoryKwargsFilterView.as_view()),

]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('category/list/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', views.CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('animal/list/', views.AnimalListView.as_view(), name='animal_list'),
    path('animal/create/', views.AnimalCreateView.as_view(), name='animal_create'),

    path('contact/', views.ContactFormView.as_view(), name='contact'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework import routers, serializers, viewsets
# from user_app.models import MyUser
#
#
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = MyUser
#         fields = ['url', 'username', 'email', 'is_staff']
#
#
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = MyUser.objects.all()
#     serializer_class = UserSerializer
#
#
# router = routers.DefaultRouter()
# router.register(r'api-users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('users/', include('user_app.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]

user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'user_app'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js h-100">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>
        {% block title %}
        Zoo
        {% endblock %}
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>

<body class="d-flex flex-column h-100">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mainapp:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mainapp:category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'mainapp:animal_list' %}">Animals</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mainapp:contact' %}">Contact</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="d-flex align-items-center">
            <span class="navbar-text me-2">Hello, {{ user.username }}</span>
            <form method="post" action="{% url 'user_app:logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-light">Logout</button>
            </form>
        </div>
        {% else %}
        <div class="d-flex">
            <a class="btn btn-outline-light me-3" href="{% url 'user_app:login' %}">Login</a>
            <a class="btn btn-outline-light" href="{% url 'user_app:register' %}">Register</a>
        </div>
        {% endif %}
    </div>
</nav>


{% block body %}
{% endblock %}

<footer
        class="footer mt-auto py-3 bg-dark d-flex flex-wrap justify-content-between align-items-center py-3 px-3 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <span class="mb-3 mb-md-0 text-white">Copyleft &#127279; Zoo 2024</span>
    </div>

    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a class="nav-link px-2 text-muted" target="_blank"
                                href="https://github.com/OtusTeam/WebPython/tree/WebPython.2023.10/"><i
                class="bi bi-github"></i></a></li>
    </ul>

</footer>

</body>

{% block scripts %}
{% endblock %}

</html>